# Generated by Django 6.0.5 on 2026-05-12 04:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kebun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_rak', models.CharField(max_length=100)),
                ('api_key', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('nomor_wa', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kebun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raks', to='monitor.kebun')),
            ],
        ),
        migrations.CreateModel(
            name='DataSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ph', models.FloatField()),
                ('tds', models.FloatField()),
                ('suhu', models.FloatField()),
                ('rak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sensor', to='monitor.rak')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
