# Generated by Django 6.0.5 on 2026-05-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rak',
            name='interval_menit',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='rak',
            name='api_key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
