# Generated by Django 6.0.5 on 2026-05-13 13:51

import django.db.models.deletion
from django.db import migrations, models


def create_api_keys(apps, schema_editor):
    Rak = apps.get_model('monitor', 'Rak')
    APIKey = apps.get_model('monitor', 'APIKey')
    existing_keys = Rak.objects.values_list('api_key', flat=True).distinct()
    for key in existing_keys:
        if key:
            APIKey.objects.get_or_create(api_key=key, defaults={'nama_alat': f'Alat {key}', 'status': 'active'})


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_rak_interval_menit_alter_rak_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('api_key', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nama_alat', models.CharField(default='Unknown Device', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Tidak Aktif')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunPython(create_api_keys, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='rak',
            name='foto',
            field=models.ImageField(blank=True, default='rak_photos/default_rak.svg', null=True, upload_to='rak_photos/'),
        ),
        migrations.AlterField(
            model_name='rak',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitor.apikey'),
        ),
    ]
