# Generated by Django 6.0.5 on 2026-06-23 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_rak_deepsleep_menit_alter_rak_interval_menit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rak',
            name='kebun',
        ),
        migrations.CreateModel(
            name='Tanaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, default='tanaman_photos/default_tanaman.svg', null=True, upload_to='tanaman_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kebun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanamans', to='monitor.kebun')),
            ],
        ),
        migrations.AddField(
            model_name='rak',
            name='tanaman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raks', to='monitor.tanaman'),
        ),
    ]
