# Generated by Django 6.0.5 on 2026-06-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_remove_rak_kebun_tanaman_rak_tanaman'),
    ]

    operations = [
        migrations.AddField(
            model_name='rak',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rak',
            name='max_ph',
            field=models.FloatField(default=6.5),
        ),
        migrations.AddField(
            model_name='rak',
            name='min_ph',
            field=models.FloatField(default=5.5),
        ),
    ]
